#:schema https://mise.en.dev/schema/mise.json

[hooks]
enter = [
  { shell = "bash", script = "command -v hum >/dev/null && source <(hum completion bash)" },
  { shell = "zsh", script = "command -v hum >/dev/null && source <(hum completion zsh)" },
  { shell = "fish", script = "type -q hum; and hum completion fish | source" },
]

[tool_alias]
varlock = "github:dmno-dev/varlock"

[tools]
bun = "latest"
varlock = { version = "latest", version_prefix = "varlock@" }
prettier = "latest"
gitleaks = "latest"
lefthook = "latest"
task = "latest"
"github:brettinternet/hum" = "latest"

[settings]
disable_backends = ["asdf"]
npm.bun = true
